#!/usr/bin/env python3
"""pipeline/submission/build_tier1.py

Tier-1 builders for native responses.

The primary path combines a full native G synthetic experiment with a
separate paired F experimental panel:

  native G treatment rows + calibrated F/C population-average ATE correction,
  followed by finite-support projection.

The older all-arms raw-response builder is retained as a testable fallback
for previously generated Phase-A files.

Usage:
    python submission/build_tier1.py --g-native-responses data/g_native.csv --f-responses data/f_responses.csv --out data/tier1_primary.csv
    python submission/build_tier1.py --raw-responses data/raw_responses.csv --out data/tier1_legacy.csv
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PIPELINE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PIPELINE_ROOT))

import pandas as pd  # noqa: E402

import survey_content as sc  # noqa: E402
from ate.calibrate_lambda import fit_calibration_model_comparison, load_ate_archive, summarize_calibration_rows  # noqa: E402
from ate.estimate_ates import estimate_raw_ates  # noqa: E402
from ate.normalize_effects import RAW_ITEM_SCALE_BOUNDS, to_percent_of_range  # noqa: E402
from calibration.calibrate_arm import calibrate_arm_to_target_ate  # noqa: E402
from calibration.external_prediction_provenance import assert_external_f_predictions_production_ready, file_sha256  # noqa: E402
from submission.final_tier1 import build_final_tier1  # noqa: E402
from submission.validate_tier1 import validate_tier1  # noqa: E402

ATE_ARCHIVE_PATH = PIPELINE_ROOT / "data" / "ate_archive.csv"
CALIBRATION_SELECTED_MODEL_PATH = PIPELINE_ROOT / "outputs" / "calibration_selected_model.json"


class CalibrationNotProductionReady(RuntimeError):
    """Raised instead of ever silently substituting M0 for production Tier-1 construction."""


def resolve_production_calibration_model(
    archive_path: Path | None = None,
    *,
    selected_model_path: Path | None = None,
) -> dict:
    """Strict production-only calibration resolution for build_final_tier1.

    UNLIKE resolve_calibration_model() below (which is a testable fallback
    for the legacy --raw-responses fixture path and silently substitutes M0
    on any archive/fit problem), this function NEVER falls back to M0. It:

    1. re-verifies, at build time (not just at the earlier calibration-fit
       time), that the external F predictions in the current archive are
       production-ready -- generated by the frozen F*, using the frozen
       R_F, frozen F prompt/compiler/config, and the frozen external panel
       (assert_external_f_predictions_production_ready already checks all
       of this; it is not reimplemented here);
    2. requires a PERSISTED calibration_selected_model.json artifact
       (written only by `scripts/run_primary_calibration.py --production`
       after its own frozen-LOSO M0/M1/M2 selection) rather than re-fitting
       the calibration map ad hoc from whatever is currently on disk;
    3. requires that artifact to be explicitly marked
       usable_for_production=True -- missing, False, or any other value
       fails closed;
    4. requires the artifact's recorded source archive hash to match the
       archive just re-verified in step 1, so a calibration fit against a
       now-superseded archive cannot be silently applied to newer data.

    Any failure raises CalibrationNotProductionReady with a clear reason.
    Does not alter the M0/M1/M2 definitions or the frozen LOSO selection
    rule in ate/calibrate_lambda.py.
    """
    archive_path = archive_path or ATE_ARCHIVE_PATH
    selected_model_path = selected_model_path or CALIBRATION_SELECTED_MODEL_PATH

    if not Path(archive_path).exists():
        raise CalibrationNotProductionReady(f"calibration archive is missing: {archive_path}")
    archive_df = pd.read_csv(archive_path)
    try:
        assert_external_f_predictions_production_ready(archive_df)
    except RuntimeError as exc:
        raise CalibrationNotProductionReady(f"external F predictions are not production-ready: {exc}") from exc

    if not Path(selected_model_path).exists():
        raise CalibrationNotProductionReady(
            f"no frozen production calibration artifact at {selected_model_path}; "
            "run `python scripts/run_primary_calibration.py --production` first -- "
            "production Tier-1 construction never fits calibration ad hoc"
        )
    try:
        model = json.loads(Path(selected_model_path).read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise CalibrationNotProductionReady(f"frozen calibration artifact at {selected_model_path} could not be loaded: {exc}") from exc

    if model.get("usable_for_production") is not True:
        raise CalibrationNotProductionReady(
            f"frozen calibration artifact at {selected_model_path} is not explicitly marked "
            f"usable_for_production=True (got {model.get('usable_for_production')!r}); "
            "re-run `python scripts/run_primary_calibration.py --production` against a fresh, "
            "non-stale archive"
        )

    recorded_hash = model.get("source_ate_archive_sha256")
    current_hash = file_sha256(archive_path)
    if not recorded_hash:
        raise CalibrationNotProductionReady(
            f"frozen calibration artifact at {selected_model_path} does not record its source "
            "archive hash; it predates this safety check and must be regenerated"
        )
    if recorded_hash != current_hash:
        raise CalibrationNotProductionReady(
            f"frozen calibration artifact was fit against a different ate_archive.csv "
            f"(recorded sha256={recorded_hash}, current sha256={current_hash}); the archive "
            "changed since calibration was frozen -- re-run `python scripts/run_primary_calibration.py --production`"
        )

    return model


def resolve_calibration_model(archive_path: Path | None = None) -> dict:
    """Select the external M0/M1/M2 ATE calibration model."""
    try:
        rows = load_ate_archive(archive_path) if archive_path else load_ate_archive()
    except ValueError as e:
        print(f"[calibration] data/ate_archive.csv is not usable ({e}); using M0 identity")
        return {"model_name": "M0", "calibration_alpha": 0.0, "calibration_lambda": 1.0, "reason": "ate_archive.csv not usable"}

    model_ate_pp = [r["model_ate"] for r in rows]
    human_ate_pp = [r["human_ate"] for r in rows]
    study_id = [r["study_id"] for r in rows]
    calibration_set_summary = summarize_calibration_rows(rows)
    if len(model_ate_pp) < 2:
        print("[calibration] fewer than 2 usable archive rows; using M0 identity")
        return {
            "model_name": "M0",
            "calibration_alpha": 0.0,
            "calibration_lambda": 1.0,
            "reason": "insufficient usable archive rows",
            "calibration_set_summary": calibration_set_summary,
        }

    try:
        fit = fit_calibration_model_comparison(model_ate_pp, human_ate_pp, study_id)
    except ValueError as e:
        print(f"[calibration] external archive is not LOSO-eligible ({e}); using M0 identity")
        return {
            "model_name": "M0",
            "calibration_alpha": 0.0,
            "calibration_lambda": 1.0,
            "reason": str(e),
            "calibration_set_summary": calibration_set_summary,
        }
    fit["calibration_set_summary"] = calibration_set_summary
    print(
        f"[calibration] {len(model_ate_pp)} archive rows -> {fit['model_name']} "
        f"(alpha={fit['calibration_alpha']:.3f}, lambda={fit['calibration_lambda']:.3f}; "
        f"LOSO RMSE M0={fit['loso_rmse_M0']:.2f}, M1={fit['loso_rmse_M1']:.2f}, M2={fit['loso_rmse_M2']:.2f})"
    )
    print(f"[calibration] primary calibration set: {calibration_set_summary}")
    return fit


def resolve_lambda_ate(archive_path: Path | None = None) -> tuple[float, dict]:
    """Compatibility shim for the legacy all-arms builder."""
    model = resolve_calibration_model(archive_path)
    return float(model["calibration_lambda"]), {"specification": model["model_name"], "fit": model}


def build_tier1(raw_responses: pd.DataFrame, condition_column: str = "condition", control_label: str = "control") -> tuple[pd.DataFrame, dict]:
    """Runs the full Phase B pipeline on an already-loaded Phase A raw
    response table. Returns (calibrated_df, report)."""
    items = sc.load_items()
    item_labels = [it["target_label"] for it in items]
    item_by_label = {it["target_label"]: it for it in items}

    lambda_ate, lambda_report = resolve_lambda_ate()
    raw_ates = estimate_raw_ates(raw_responses, item_labels, condition_column=condition_column, control_label=control_label)
    calibration_diagnostics = []

    calibrated = raw_responses.copy()
    for _, row in raw_ates.iterrows():
        item = item_by_label[row["outcome"]]
        low, high = RAW_ITEM_SCALE_BOUNDS[item["scale"]]
        target_ate_pp = lambda_ate * to_percent_of_range(row["raw_ate"], low, high)
        target_ate_native = target_ate_pp / 100 * (high - low)

        control_mask = calibrated[condition_column] == control_label
        treatment_mask = calibrated[condition_column] == row["condition"]
        control_values = calibrated.loc[control_mask, item["target_label"]].tolist()
        raw_treatment_values = calibrated.loc[treatment_mask, item["target_label"]].tolist()
        adjusted = calibrate_arm_to_target_ate(control_values, raw_treatment_values, target_ate_pp, low, high)
        calibrated.loc[treatment_mask, item["target_label"]] = adjusted
        achieved_ate = float(pd.Series(adjusted).mean() - pd.Series(control_values).mean())
        calibration_diagnostics.append(
            {
                "condition": row["condition"],
                "outcome": item["target_label"],
                "target_ate": target_ate_native,
                "achieved_ate": achieved_ate,
                "absolute_error": abs(achieved_ate - target_ate_native),
            }
        )

    outcome_rows = [sc.compute_outcomes(row.to_dict()) for _, row in calibrated.iterrows()]
    outcome_df = pd.DataFrame(outcome_rows)
    # 6 of the 13 outcomes ARE a raw item verbatim (OUTCOME_COMPOSITES's "item"
    # kind, e.g. trust_post) -- drop the pre-existing raw-item column before
    # concatenating so pandas doesn't rename the duplicate to "trust_post.1";
    # outcome_df's own column already carries the identical (calibrated) value.
    calibrated = calibrated.drop(columns=[c for c in outcome_df.columns if c in calibrated.columns])
    calibrated = pd.concat([calibrated.reset_index(drop=True), outcome_df], axis=1)
    calibration_diagnostics_df = pd.DataFrame(calibration_diagnostics)
    validation_report = validate_tier1(calibrated, calibration_diagnostics=calibration_diagnostics_df)
    outcome_ates = estimate_raw_ates(calibrated, list(sc.OUTCOME_COMPOSITES.keys()), condition_column=condition_column, control_label=control_label)

    return calibrated, {
        "lambda_ate": lambda_ate,
        "lambda_report": lambda_report,
        "raw_ates": raw_ates,
        "outcome_ates": outcome_ates,
        "calibration_diagnostics": calibration_diagnostics_df,
        "validation_report": validation_report,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw-responses", type=Path, help="Legacy all-arms Phase A output CSV")
    parser.add_argument("--g-native-responses", type=Path, help="Full native G response CSV: control plus all 16 treatments for the same 1000 donors")
    parser.add_argument("--f-responses", type=Path, help="Paired F experimental response CSV")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--outputs-dir", type=Path, help="Directory for builder audit artifacts; defaults to pipeline/outputs")
    parser.add_argument("--expected-n-g", type=int, default=1000, help="Expected number of G donors in each condition")
    parser.add_argument("--expected-n-f", type=int, default=500, help="Expected number of F profiles in each condition")
    parser.add_argument(
        "--allow-unfrozen-f-protocol-for-fixture",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args()

    if args.g_native_responses or args.f_responses:
        if not args.g_native_responses or not args.f_responses:
            parser.error("--g-native-responses and --f-responses must be supplied together")
        g_native = pd.read_csv(args.g_native_responses)
        f_responses = pd.read_csv(args.f_responses)
        model = resolve_production_calibration_model()
        calibrated, report = build_final_tier1(
            g_native,
            f_responses,
            model,
            expected_n_g=args.expected_n_g,
            expected_n_f=args.expected_n_f,
            outputs_dir=args.outputs_dir,
            require_frozen_f_protocol=not args.allow_unfrozen_f_protocol_for_fixture,
        )
    elif args.raw_responses:
        raw_responses = pd.read_csv(args.raw_responses)
        print(f"loaded {len(raw_responses)} raw responses from {args.raw_responses}")
        calibrated, report = build_tier1(raw_responses)
    else:
        parser.error("supply either --raw-responses or the DELTA --g-control-responses/--f-responses pair")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    calibrated.to_csv(args.out, index=False)
    print(f"\nwrote {len(calibrated)} rows to {args.out}")
    if "final_ate_audit" in report:
        validation = report.get("validation_report", {})
        print(f"primary final builder: {len(report['final_ate_audit'])} ATE audit rows; no explicit HTE model")
        print(f"Tier-1 validation: {validation}")
    elif "validation_report" in report:
        print(f"lambda_ate used: {report['lambda_ate']:.4f} ({report['lambda_report']['specification']})")
        print(f"Tier-1 validation: {report['validation_report']}")
    else:
        print("wrote output; no validation report returned")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
